### ISSUE TITLE
Reporting issue does not display responsive images with srcset attribute

### ISSUE THREAD

**Issue by rubenmontes-sofomo** [marker-io/browser-sdk#10]
When reporting issue in a screen which uses responsive images, the HTML will look like this 

```
<img srcset="elva-fairy-480w.jpg 480w,
             elva-fairy-800w.jpg 800w"
     sizes="(max-width: 600px) 480px,
            800px"
     src="elva-fairy-800w.jpg"
     alt="Elva dressed as a fairy">
```

The images are not displayed.

**Comment by olivierkaisin** [comment]
Hi @rubenmontes-sofomo, is your site protected by HTTP Basic Authentication? 

If that's the case, then it would explain why your images aren't showing. The good news is: we are working on a fix to support all HTTP Basic Auth protected websites, it should be live by the end of this week, or early next week 🚀

**Comment by emilevictorportenart** [comment]
@rubenmontes-sofomo Could you double-check if your website is under Basic auth? If yes, can you follow this guide https://help.marker.io/en/articles/5937791-basic-authentication and let us know if it's working?

**Comment by emilevictorportenart** [comment]
After trying it out on our side with the same method, I can confirm it's working. Please review your basic auth settings https://help.marker.io/en/articles/5937791-basic-authentication  or you can also try to use the native browser technology https://help.marker.io/en/articles/4621840-widget-javascript-api#h_579845d126
