### ISSUE TITLE
Provide CommonJS module export

### ISSUE THREAD

**Issue by kevin51jiang** [marker-io/browser-sdk#11]
Currently it breaks with NextJS. 

Since NextJS is prerendered serverside, and it uses Nodejs which uses commonjs exports instead, the `export default` breaks it (expects `module.exports = foo`)

To fix this, maybe it could be compiled into separate files or into UMD (Universal module definition) by something like rollup

**Comment by olivierkaisin** [comment]
Hi @kevin51jiang, good point here. We'll integrate these changes in an upcoming release. Thanks for suggesting!
