### ISSUE TITLE
widget.setReporter is not a function

### ISSUE THREAD

**Issue by Santoshgoodworklabs** [marker-io/browser-sdk#12]
After initialization when i am trying to execute setReporter getting this error.

![image](https://user-images.githubusercontent.com/97423343/155948534-8f478bef-2c45-4acb-9d86-6d64fa7c6f5e.png)

**Comment by olivierkaisin** [comment]
Hi @Santoshgoodworklabs,

Since `markerSDK.loadWidget({ ... })` returns a `Promise`, can you confirm you are calling `.setReporter()` on the resolved value?

Here is the example provided in our readme:

```
import markerSDK from '@marker.io/browser';

const widget = await markerSDK.loadWidget({ destination: 'abcd1234567890' });
```

Let me know 🚀
