### ISSUE TITLE
Provide typings for typescript projects

### ISSUE THREAD

**Issue by crashtimer** [marker-io/browser-sdk#2]

**Comment by olivierkaisin** [comment]
Hi @crashtimer, we are definitely planning to provide typings.

 We'll take care of that as soon as we can, but please don't hesitate to give us a hand if you want to.

Thanks!

**Comment by bramski** [comment]
One year ago. No typings. I will take this on.

**Comment by bramski** [comment]
Resolved by:
https://github.com/marker-io/browser-sdk/pull/14

**Comment by bramski** [comment]
@olivierkaisin Request you merge this and release right away. I'm a customer integrating this into our site for UAT and need it within 2 weeks. I don't like referring to my own github repos in production code.

**Comment by olivierkaisin** [comment]
Released today in `0.13.0`
