### ISSUE TITLE
Devtools Console only shows `shim.js`

### ISSUE THREAD

**Issue by ariperez** [marker-io/browser-sdk#20]
I'm currently using redwood.js with marker.io.  If marker-io loads in any form, all messages in the Devtools console show up with their source as `/shim.js`.  Any ideas how I can stop this behavior? 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/2553469/211210398-1a9d5628-a22f-44ed-8e4c-08889d59f868.png">

**Comment by emilevictorportenart** [comment]
I'm not sure 100% but I think what you're looking for is the silent mode. Is it fixing your issue?
https://github.com/marker-io/browser-sdk#-enabling-markerio-silent-mode

<img width="972" alt="CleanShot 2023-01-11 at 12 23 58@2x" src="https://user-images.githubusercontent.com/921074/211794199-5d6c8660-475b-4693-a86c-5ea82cf2e0b7.png">

**Comment by olivierkaisin** [comment]
Hi @ariperez,

The file name modification is a side-effect of our console logs recorder being activated, but unfortunately, there is currently no way for us to avoid it as it is a consequence of a browser limitation.

You could disable the recorder on your widget, but you would loose the entire console.logs feature, so I wouldn't recommend it.

A better solution I would personally recommend is to disable Marker.io in your local development environment, but to keep it enabled in staging and production. That way your logs are left untouched while working on new features, but you will keep getting detailed console logs when customers report bugs using Marker.io.

Let me know if that helps,
Olivier

**Comment by MatthewAry** [comment]
You could at least tell us how to disable the recorder. :)
