### ISSUE TITLE
Capture is not a function

### ISSUE THREAD

**Issue by Jelbert** [marker-io/browser-sdk#25]
Hello, I don't know if this is a bug, I followed the documentation (https://marker.io/blog/integrate-web-app-browser-sdk) and got error. Please help. Thanks

I'm using vuejs 3.

![image](https://github.com/marker-io/browser-sdk/assets/5991069/50347a92-309d-4843-b07f-323c4387b2da)

```javascript
const widget = markerSDK.loadWidget({
    project: 'abc1234',

    reporter: {
        email: 'john@clientwebsite.com',
        fullName: 'John Smith',
    },
});

function reportABug(){
      widget.capture()
}
```

**Comment by Jelbert** [comment]
SOLVE:

```javascript
function reportABug(){
    widget.then(value => {
        value.capture();
    });
}
```

**Comment by emilevictorportenart** [comment]
Happy to hear you got it solved. We're going to update the documentation to make it clearer!
