### ISSUE TITLE
silent mode is not supported

### ISSUE THREAD

**Issue by crashtimer** [marker-io/browser-sdk#3]
Looking at the doc and see silent mode property in config option while initialisation, but can't find this in source files of the npm package and it throws a warning in console

**Comment by paavo** [comment]
Same problem here
`(Marker.io SDK) unknown param "silent" (need to upgrade?)`

**Comment by olivierkaisin** [comment]
Hi @crashtimer, sorry for the long waiting time, we've added support for silent mode in version 0.11.0!

Thanks!
