### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by karthik-hr** [marker-io/browser-sdk#32]
version: "@marker.io/browser": "^0.19.0"

Following Error logs been found in console
<img width="1210" alt="Screenshot 2023-09-29 at 11 39 04 PM" src="https://github.com/marker-io/browser-sdk/assets/63744048/45079343-0466-4561-952e-f3c952ac78be">

<img width="1436" alt="Screenshot 2023-09-29 at 11 39 17 PM" src="https://github.com/marker-io/browser-sdk/assets/63744048/58a8cfbd-efc2-4233-b791-89a32ba591ca">

**Comment by olivierkaisin** [comment]
This error comes from the widget itself (bug in our session recording library) and not the browser SDK. I've logged this in our private issue tracker and we'll fix it asap. 

Thanks for reporting!
