### ISSUE TITLE
Show us how to disable the console.log interception

### ISSUE THREAD

**Issue by MatthewAry** [marker-io/browser-sdk#35]
## What's the issue?

When a customer is on the starter plan, it appears that we collect network logs/console logs and there's no way to disable this behavior in the UI.

## What's expected?

On starter plan, never capture console logs nor network requests.

## Customer description

> I know why this feature exists, but I need to use marker in dev mode and I can't have it interfering with me being able to determine where the log call came from in console dev tools. [#20](https://github.com/marker-io/browser-sdk/issues/20) explains why, but never told us how it can be disabled. How can we disable the console.log interception in marker?

[Show us how to disable the console.log interception · Issue #35 · marker-io/browser-sdk](https://github.com/marker-io/browser-sdk/issues/35)

**Comment by emilevictorportenart** [comment]
Hey @MatthewAry the best way to disable console.log is to go to your project settings in app.marker.io and disable the console logs like on this screenshot.

![CleanShot 2024-02-14 at 07 23 22](https://github.com/marker-io/browser-sdk/assets/921074/58ce75fc-34ce-43d1-b512-aa561018035c)

Please try and let me know if it works for you :)

**Comment by MatthewAry** [comment]
Yes. I contacted support about this and they told me the same thing. I'm not even paying for console logging, I'm on the starter plan. In other words, the checkbox you want me to click is unselectable to me.

Yet, As of the last time I tried using the library I was still being affected by this issue.

**Comment by emilevictorportenart** [comment]
oh i understand now. is ut correct to say that youre on the starter plan and the widget is still collecting logs? if yes iets a big and we’ll fix ut asap

**Comment by MatthewAry** [comment]
Yup
