### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'tagName')

### ISSUE THREAD

**Issue by MikePrus** [marker-io/browser-sdk#37]
GitHub Issue: [https://github.com/marker-io/browser-sdk/issues/37](https://github.com/marker-io/browser-sdk/issues/37)

![image](https://github.com/marker-io/browser-sdk/assets/921074/db976d11-e005-41db-b569-de1dc2a44511)

### Issue Context

I have Vite+React TS app and use @tinymce/tinymce-react editor for creating content, I get this issue when I remove typed text in the editor.

I created a [GitHub repo](https://github.com/AgentPrus/marker.io-sandbox?tab=readme-ov-file#environment-variables) where this issue is reproduced, so have a look.

Will be great to fix this ASAP or maybe give me some feedback on how to handle this on my end.

**Comment by olivierkaisin** [comment]
We have released a fix early this week that solves this issue 🎉 

Please let us know if it works for you!

**Comment by MikePrus** [comment]
@olivierkaisin thanks for the quick fix everything works well!
