### ISSUE TITLE
Add missing options

### ISSUE THREAD

**Issue by paavo** [marker-io/browser-sdk#4]
Some options are missing in the SDK. 
May you add them @emilevictorportenart?

```
(Marker.io SDK) unknown param "silent" (need to upgrade?)
(Marker.io SDK) unknown param "source" (need to upgrade?)
(Marker.io SDK) unknown param "ssr" (need to upgrade?)
```

**Comment by olivierkaisin** [comment]
Hi @paavo, sorry for the long waiting time. These parameters are now all supported in version 0.11.0

Thanks!
