### ISSUE TITLE
(Marker.io) Could not record fetch(): e.hasOwnProperty is not a function TypeError: e.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by rickypag** [marker-io/browser-sdk#42]
In our React application we are using `@marker.io/browser` to connect it to Marker.io.

It works fine, however we get an annoying warning everytime we swtich page
<img width="608" alt="image" src="https://github.com/user-attachments/assets/3b9ec25d-ce2d-4e68-8248-c5172be7298d">

How we are using the library is that we are just activating the widget at the top of our application (i.e. only the first time it is rendered)

```
const App = () => {
   ...

   React.useEffect(() => {
      const loadWidget = async () => {
         await markerSDK.loadWidget({
            project: projectId
        });
      }
      loadWidget()
   }, [])

   ...
}
```

I suppose this is an issue with Marker.io directly.
Is this known?

**Comment by olivierkaisin** [comment]
Hi @rickypag,

Thank you for reporting this and for your patience.  
We released an update yesterday, and this bug should now be resolved in the latest version.  

Please let me know if it works for you!  
Olivier
