### ISSUE TITLE
Disable screenshots

### ISSUE THREAD

**Issue by erback** [marker-io/browser-sdk#8]
Hi! Im looking for a way to disable automatic screenshots - can this be done somehow via the sdk? Been looking through the documentation but cannot find any info. The reason for this is GDPR - I dont want people to accidently submit personal data due to automatic screenshots.

**Comment by emilevictorportenart** [comment]
Hey @erback it's not possible to do it yet but it's on the roadmap for this year and we'll make sure to send you an email when it's released!

**Comment by emilevictorportenart** [comment]
Hey Erik, I've added your vote in our roadmap feature https://marker-io.canny.io/feature-request/p/no-screenshot-reporting I'll close this issue and let you know when we release it!
