### ISSUE TITLE
cannot install the package

### ISSUE THREAD

**Issue by sohumsen** [marker-io/browser-sdk#9]
When i try to install the package by `npm install -s @marker.io/browser` i get this error 

`The splatting operator '@' cannot be used to reference variables in an expression. '@marker' can be used only as an argument to a command. To reference variables in an     
expression use '$marker'. `

perhaps there is an alias that we can use to install the package without using "@"?

any help appreciated
`

**Comment by olivierkaisin** [comment]
Seems that you are using powershell. Can you try running `npm install -s '@marker.io/browser'` instead?
